# Generated by Django 4.1.2 on 2022-10-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=200, null=True)),
                ('backend', models.BooleanField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('bio', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
